version: "3.8"

services:
  react-prod:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vaccine_react_prod
    ports:
      - "5173:80"
    restart: always

  # react-dev:
  #   build:s
  #     context: .
  #     dockerfile: Dockerfile.dev
  #   container_name: vaccine_react_dev
  #   ports:
  #     - "5173:5173"
  #   volumes:
  #     - .:/app
  #     - /app/node_modules
  #   environment:
  #     - NODE_ENV=development
